openapi: 3.0.3
info:
  title: TeamBoard API
  version: 1.0.0
servers:
  - url: /api

security:
  - bearerAuth: []

paths:

  /user/register:
    post:
      security: []
      summary: Register a new user
      tags: [ User ]
      operationId: register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Registration successful
        '400':
          description: Username or password missing
        '409':
          description: Username already exists

  /user/login:
    post:
      security: []
      summary: Login user
      tags: [ User ]
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Username or password missing
        '401':
          description: Invalid credentials

  /user/{id}:
    delete:
      summary: Delete user by ID
      tags: [ User ]
      operationId: deleteUserById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: User deleted successfully
        '404':
          description: User not found

  /projects:
    get:
      summary: Get all projects (paginated)
      tags: [ Project ]
      operationId: getAllProjects
      parameters:
        - $ref: "#/components/parameters/Page"
        - $ref: "#/components/parameters/Size"
        - $ref: "#/components/parameters/Sort"
      responses:
        '200':
          description: Paginated list of projects
          headers:
            X-Total-Count:
              $ref: '#/components/headers/X-Total-Count'
            X-Page-Size:
              $ref: '#/components/headers/X-Page-Size'
            X-Page-Number:
              $ref: '#/components/headers/X-Page-Number'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProjectResponse'
    post:
      summary: Create a new project
      tags: [ Project ]
      operationId: createProject
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectRequest'
      responses:
        '201':
          description: Project created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectResponse'
        '400':
          description: Invalid project details

  /projects/{id}:
    get:
      summary: Get project by ID
      tags: [ Project ]
      operationId: getProjectById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Project found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectResponse'
        '404':
          description: Project not found
    put:
      summary: Update project by ID
      tags: [ Project ]
      operationId: updateProjectById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectRequest'
      responses:
        '200':
          description: Project updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectResponse'
        '400':
          description: Invalid project details
        '403':
          description: Forbidden (not owner)
        '404':
          description: Project not found
    delete:
      summary: Delete project by ID
      tags: [ Project ]
      operationId: deleteProjectById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Project deleted
        '403':
          description: Forbidden (not owner)
        '404':
          description: Project not found

  /me:
    get:
      summary: Get current user info from JWT token
      tags: [ User ]
      operationId: me
      responses:
        '200':
          description: User info returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
        '401':
          description: Missing or invalid token

  /column:
    get:
      summary: Get all columns
      tags: [ Column ]
      operationId: getAllColumns
      responses:
        '200':
          description: List of all columns
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ColumnResponse'
    post:
      summary: Create a new column
      tags: [ Column ]
      operationId: createColumn
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ColumnRequest'
      responses:
        '201':
          description: Column created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ColumnResponse'
        '404':
          description: Project not found
        '400':
          description: Invalid column details

  /column/{id}:
    get:
      summary: Get column by ID
      tags: [ Column ]
      operationId: getColumnById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Column found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ColumnResponse'
        '404':
          description: Column not found
    put:
      summary: Update column by ID
      tags: [ Column ]
      operationId: updateColumnById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ColumnRequest'
      responses:
        '200':
          description: Column updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ColumnResponse'
        '404':
          description: Column or project not found
        '400':
          description: Invalid column details
    delete:
      summary: Delete column by ID
      tags: [ Column ]
      operationId: deleteColumnById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Column deleted
        '404':
          description: Column not found

  /card:
    post:
      summary: Create a new card
      tags: [ Card ]
      operationId: createCard
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CardRequest'
      responses:
        '201':
          description: Card created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardResponse'
        '404':
          description: Card not found
        '400':
          description: Invalid card details

  /card/{id}:
    get:
      summary: Get card by ID
      tags: [ Card ]
      operationId: getCardById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Card found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardResponse'
        '404':
          description: Card not found
    put:
      summary: Update card by ID
      tags: [ Card ]
      operationId: updateCardById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CardRequest'
      responses:
        '200':
          description: Card updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardResponse'
        '404':
          description: Card or column not found
        '400':
          description: Invalid card details
    delete:
      summary: Delete card by ID
      tags: [ Card ]
      operationId: deleteCardById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Card deleted
        '404':
          description: Card not found

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        password:
          type: string
        email:
          type: string
    LoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    ProjectRequest:
      type: object
      required:
        - title
      properties:
        title:
          type: string
        description:
          type: string
    ProjectResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        ownerUsername:
          type: string
    ColumnRequest:
      type: object
      required:
        - title
        - position
        - projectId
      properties:
        title:
          type: string
        position:
          type: integer
        projectId:
          type: integer
          format: int64
    ColumnResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        position:
          type: integer
        projectId:
          type: integer
          format: int64
    CardRequest:
      type: object
      required:
        - title
        - assignedTo
        - columnId
      properties:
        title:
          type: string
        description:
          type: string
        assignedTo:
          type: integer
          format: int64
        columnId:
          type: integer
          format: int64
    CardResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        assignedTo:
          type: integer
          format: int64
        columnId:
          type: integer
          format: int64

  headers:
    X-Total-Count:
      schema:
        format: int32
        type: integer
      description: Total amount of elements for this query
    X-Page-Number:
      schema:
        format: int32
        type: integer
      description: Page number starting from 0
    X-Page-Size:
      schema:
        format: int32
        type: integer
      description: Page size

  parameters:
    Page:
      name: page
      description: Page number
      schema:
        format: int32
        default: 0
        type: integer
      in: query
      required: false
    Size:
      name: size
      description: Page size
      schema:
        format: int32
        default: 10
        type: integer
      in: query
      required: false
    Sort:
      name: sort
      description: 'The field to be sorted, direction (e.g.: id,desc)'
      schema:
        default: 'title,asc'
        type: string
      in: query
      required: false